AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

#
# Common Ronin style rules:
#
Layout/FirstArrayElementIndentation: { Exclude: ['spec/**/*'] }
Layout/LineLength: { Enabled: false }
Layout/SpaceAroundEqualsInParameterDefault: { EnforcedStyle: 'no_space' }
Lint/ConstantDefinitionInBlock: { Exclude: ['spec/**/*'] }
Metrics: { Enabled: false }
Style/SymbolArray: { EnforcedStyle: 'brackets' }
Style/IfInsideElse: { Enabled: false } # Offense count: 1
Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    default: '{}'
    '%i': '[]'
    '%I': '[]'
    '%w': '[]'
    '%W': '[]'
Style/UnlessElse: { Enabled: false }
Bundler/OrderedGems: { Enabled: false }
Style/Next: { Enabled: false }
Style/HashSyntax: { Enabled: false }
Naming/BlockForwarding: { Enabled: false }
Naming/RescuedExceptionsVariableName: { Enabled: false }
Lint/ReturnInVoidContext: { Enabled: false }
Lint/NoReturnInBeginEndBlocks: { Enabled: false }
Gemspec/DeprecatedAttributeAssignment: { Enabled: false }
Layout/EmptyLinesAroundClassBody: { Enabled: false }
Layout/EmptyLineAfterMagicComment: { Enabled: false }
Layout/FirstArgumentIndentation: { Enabled: false }
Layout/BeginEndAlignment: { Enabled: false }
Layout/RescueEnsureAlignment: { Enabled: false }
Layout/HashAlignment: { Enabled: false }
Layout/SpaceAfterComma: { Enabled: false }
Layout/SpaceInsideHashLiteralBraces: { Enabled: false }
Style/MultilineBlockChain: { Enabled: false }
Style/NumericLiterals: { Enabled: false }
Style/RedundantInterpolation: { Enabled: false }
Style/FormatString: { Enabled: false }
Style/RedundantSelf: { Enabled: false }
Style/FetchEnvVar: { Enabled: false }
Style/BlockDelimiters: { Enabled: false }
Style/ClassCheck: { Enabled: false }
Style/FrozenStringLiteralComment: { Exclude: ['spec/**/*'] }
Style/GuardClause: { Enabled: false }
Style/IfUnlessModifier: { Enabled: false }
Style/SpecialGlobalVars: { Enabled: false }
Lint/ElseLayout: { Enabled: false }
Layout/ExtraSpacing:
  AllowForAlignment: true
  AllowBeforeTrailingComments: true
  ForceEqualSignAlignment: true
Lint/EmptyClass: { Exclude: ['spec/**/*'] }
Lint/SuppressedException: { AllowComments: true }
Lint/UnusedMethodArgument: { Enabled: false }
Lint/UnusedBlockArgument: { Enabled: false }
Style/AccessorGrouping: { Enabled: false }
Style/KeywordParametersOrder: { Enabled: false }
Style/Lambda: { EnforcedStyle: 'literal' }
Style/MutableConstant: { Enabled: false }
Style/RedundantReturn: { Enabled: false }
Style/SafeNavigation: { Enabled: false }
Style/WordArray: { Enabled: false }
Layout/BlockAlignment: { Enabled: false }
# Style/EmptyMethod: { Exclude: ['spec/**/*'] }
Style/NumericPredicate: { Enabled: false }
Style/OptionalArguments: { Enabled: false }
Style/ParenthesesAroundCondition: { Enabled: false }
Style/PreferredHashMethods: { EnforcedStyle: 'verbose' }
Style/QuotedSymbols: { EnforcedStyle: 'double_quotes' }
Style/RedundantRegexpEscape: { Enabled: false }
Style/RescueStandardError: { Enabled: false }
Style/SoleNestedConditional: { Enabled: false }
Layout/AssignmentIndentation: { Enabled: false }
Style/StringLiterals: { Enabled: false }
Layout/SpaceBeforeComma: { Enabled: false }

# rubocop cannot tell that rubygems_mfa_required is enabled in gemspec.yml
Gemspec/RequireMFA: { Enabled: false }

# make an exception for our gemspec code
Gemspec/DuplicatedAssignment: { Exclude: ['ronin-payloads.gemspec'] }

#
# ronin-payload specific exceptions:
#
Layout/ArgumentAlignment: { Exclude: ['spec/rust_payload_spec.rb'] }

Style/EmptyMethod:
  Exclude:
    - 'lib/ronin/payloads/payload.rb'
    - 'spec/**/*'

Naming/ClassAndModuleCamelCase:
  AllowedNames:
    - X86_64

# robucop mistakes :x86_64 for a "symbol number"
Naming/VariableNumber:
  AllowedIdentifiers:
    - x86_64

# this is a bug in rubocop
Style/FormatStringToken:
  Exclude:
    - 'lib/ronin/payloads/builtin/cmd/powershell/reverse_shell.rb'
    - 'spec/builtin/cmd/powershell/reverse_shell_spec.rb'

# rubocop does not recognize empty-line continuations
Layout/LineContinuationSpacing: { Exclude: ['lib/ronin/payloads/builtin/shellcode/**/*.rb'] }
